# Missing Indicator Imputation

In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.impute import MissingIndicator,SimpleImputer

In [2]:
df = pd.read_csv('train (5).csv', usecols=['Age', 'Fare', 'Survived'])
df.head()

,Survived,Age,Fare
0,0,22.0,7.2500
1,1,38.0,71.2833
2,1,26.0,7.9250
3,1,35.0,53.1000
4,0,35.0,8.0500


## Create X & Y

In [3]:
x = df.drop(columns=['Survived'])
y = df['Survived']

## Train & Test Split

In [4]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [5]:
x_train.head()

,Age,Fare
30,40.0,27.7208
10,4.0,16.7000
873,47.0,9.0000
182,9.0,31.3875
876,20.0,9.8458


## Review Without “Missing Indicator Method” Technique

In [6]:
si = SimpleImputer()
x_train_trf = si.fit_transform(x_train)
x_test_trf = si.fit_transform(x_test)

In [7]:
x_train_trf

array([[ 40.        ,  27.7208    ],
       [  4.        ,  16.7       ],
       [ 47.        ,   9.        ],
       ...,
       [ 71.        ,  49.5042    ],
       [ 29.78590426, 221.7792    ],
       [ 29.78590426,  25.925     ]])

In [8]:
x_test_trf

array([[ 42.    ,  26.2875],
       [ 21.    ,   8.05  ],
       [ 24.    ,  65.    ],
       [ 28.    ,  56.4958],
       [ 17.    ,   7.925 ],
       [ 30.    ,   7.8958],
       [ 80.    ,  30.    ],
       [ 25.    ,   7.25  ],
       [ 50.    , 133.65  ],
       [ 25.    ,  26.    ],
       [ 35.    ,  26.    ],
       [ 35.    ,  90.    ],
       [ 55.    ,  16.    ],
       [ 29.3728,  56.4958],
       [ 29.3728,  56.4958],
       [ 19.    ,   7.8542],
       [ 29.3728,  15.2458],
       [ 49.    ,   0.    ],
       [ 18.    ,  14.4542],
       [ 65.    ,   7.75  ],
       [ 18.    , 108.9   ],
       [ 29.3728,  22.3583],
       [ 16.    ,  18.    ],
       [ 21.    ,   9.825 ],
       [ 19.    ,   6.75  ],
       [  1.    ,  11.1333],
       [ 50.    ,  10.5   ],
       [ 37.    ,  53.1   ],
       [ 28.    ,   9.5   ],
       [ 54.    ,  14.    ],
       [ 20.    ,   7.925 ],
       [ 36.    ,   0.    ],
       [  6.    ,  31.275 ],
       [ 29.3728,  50.    ],
       [ 40.  

## Call Logistic Regression

In [9]:
from sklearn.linear_model import LogisticRegression

In [11]:
clf = LogisticRegression()

clf.fit(x_train_trf,y_train)

y_pred = clf.predict(x_test_trf)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6145251396648045

## Define Missing Indicator

In [12]:
mi = MissingIndicator()
mi.fit(x_train)

,missing_values,nan
,features,'missing-only'
,sparse,'auto'
,error_on_new,True


In [13]:
MissingIndicator()

,missing_values,nan
,features,'missing-only'
,sparse,'auto'
,error_on_new,True


In [14]:
mi.features_

array([0])

In [16]:
x_train_missing = mi.transform(x_train)

x_train_missing

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

## Transform: Train Missing

In [17]:
x_test_missing = mi.transform(x_test)

x_test_missing

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

## Transform: Test Missing

In [18]:
x_train['Age_NA'] = x_train_missing

x_test

,Age,Fare
707,42.0,26.2875
37,21.0,8.0500
615,24.0,65.0000
169,28.0,56.4958
68,17.0,7.9250
...,...,...
89,24.0,8.0500
80,22.0,9.0000
846,NaN,69.5500
870,26.0,7.8958


## Create New Column

In [19]:
x_test['Age_NA'] = x_test_missing

x_train

,Age,Fare,Age_NA
30,40.0,27.7208,False
10,4.0,16.7000,False
873,47.0,9.0000,False
182,9.0,31.3875,False
876,20.0,9.8458,False
...,...,...,...
534,30.0,8.6625,False
584,NaN,8.7125,True
493,71.0,49.5042,False
527,NaN,221.7792,True


## Writing Code again and Check Accuracy

In [20]:
si = SimpleImputer()

x_train_trf2 = si.fit_transform(x_train)
x_test_trf2 = si.fit_transform(x_test)

In [21]:
from sklearn.linear_model import LogisticRegression

In [22]:
clf = LogisticRegression()
clf.fit(x_train_trf2, y_train)
y_pred = clf.predict(x_test_trf2)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6312849162011173